#pragma once

#include "Point.hpp"

namespace Slic3r {

enum class ScaffoldHeadSize : uint8_t { Light, Heavy };   // head radius w or 2w, w the slice's support toolpath width

struct ScaffoldPoint {
    Vec3f            pos = Vec3f::Zero();                 // object raw-mesh frame (ModelObject::raw_mesh())
    ScaffoldHeadSize size = ScaffoldHeadSize::Light;
    bool             enforced = false;

    bool operator==(const ScaffoldPoint &o) const { return pos == o.pos && size == o.size && enforced == o.enforced; }
    bool operator!=(const ScaffoldPoint &o) const { return !(*this == o); }
    template<class Archive> void serialize(Archive &ar) { ar(pos, size, enforced); }
};

using ScaffoldPoints = std::vector<ScaffoldPoint>;

enum class ScaffoldPointsStatus : uint8_t { NoPoints, AutoGenerated, UserModified };

enum class ScaffoldTipResult : uint8_t { Routed, Filtered, Unrouted, Neck, Merged, Wall };

// What one scaffold slice of one PrintObject did with its tips, in the object raw-mesh frame.
struct ScaffoldRecord {
    struct Tip { Vec3f pos; ScaffoldHeadSize size; bool enforced; ScaffoldTipResult result; };
    std::vector<Tip>   tips;          // baked: one per list point, in list order; auto: the tips handed to draw
    std::vector<Vec3f> bare_islands;  // where an island prints with no tip holding it
    bool               baked = false, stale = false;
    Matrix3d           pose = Matrix3d::Identity();   // linear part of the first model instance's matrix
    double             toolpath_width_mm = 0.;        // w, the slice's support toolpath width
};

// The routed tips of a record, as Generate bakes them.
inline ScaffoldPoints scaffold_points_from(const ScaffoldRecord &record)
{
    ScaffoldPoints points;
    for (const ScaffoldRecord::Tip &tip : record.tips)
        if (tip.result == ScaffoldTipResult::Routed)
            points.push_back({ tip.pos, tip.size, tip.enforced });
    return points;
}

} // namespace Slic3r

namespace cereal {   // Point.hpp serializes Transform3d but not Matrix3d; kept here, out of the precompiled header
template<class Archive> void load(Archive &ar, Slic3r::Matrix3d &m) { ar.loadBinary((char *) m.data(), sizeof(double) * 9); }
// Deduced rather than taking const Matrix3d&: Eigen's implicit converting constructor would bind a Vec3f or Vec3d to
// that reference, and cereal would then count two save functions for every vector it writes.
template<class Archive, class T, std::enable_if_t<std::is_same<T, Slic3r::Matrix3d>::value, int> = 0>
void save(Archive &ar, const T &m) { ar.saveBinary((const char *) m.data(), sizeof(double) * 9); }
}
