#pragma once

#include "Point.hpp"

namespace Slic3r {

enum class ScaffoldHeadSize : uint8_t { Light, Heavy };   // head radius w or 2w, w the slice's support toolpath width

struct ScaffoldPoint {
    Vec3f            pos = Vec3f::Zero();                 // object raw-mesh frame (ModelObject::raw_mesh())
    ScaffoldHeadSize size = ScaffoldHeadSize::Light;
    bool             enforced = false;
    // The approach axis in the raw-mesh frame: the direction from `pos` along the neck toward the pillar, straight down
    // (0, 0, -1) for a head under an overhang, as the builder's head axes run. Zero on a point that is not enforced
    // takes the neck axis the planner would lean there; zero on an enforced one aims the head along the mesh normal.
    // A drag in the gizmo that moves the point clears its axis.
    Vec3f            axis = Vec3f::Zero();

    bool operator==(const ScaffoldPoint &o) const { return pos == o.pos && size == o.size && enforced == o.enforced && axis == o.axis; }
    bool operator!=(const ScaffoldPoint &o) const { return !(*this == o); }
    template<class Archive> void serialize(Archive &ar) { ar(pos, size, enforced, axis); }
};

using ScaffoldPoints = std::vector<ScaffoldPoint>;

enum class ScaffoldPointsStatus : uint8_t { NoPoints, AutoGenerated, UserModified };

} // namespace Slic3r

namespace cereal {   // Point.hpp serializes Transform3d but not Matrix3d; kept here, out of the precompiled header
template<class Archive> void load(Archive &ar, Slic3r::Matrix3d &m) { ar.loadBinary((char *) m.data(), sizeof(double) * 9); }
// Deduced rather than taking const Matrix3d&: Eigen's implicit converting constructor would bind a Vec3f or Vec3d to
// that reference, and cereal would then count two save functions for every vector it writes.
template<class Archive, class T, std::enable_if_t<std::is_same<T, Slic3r::Matrix3d>::value, int> = 0>
void save(Archive &ar, const T &m) { ar.saveBinary((const char *) m.data(), sizeof(double) * 9); }
}
